"""Canonically-seeded profile anomalies imported from TestGen."""
from __future__ import annotations

PROFILE_ANOMALY_TYPES = [{'anomaly_type_id': '1001',
  'anomaly_type': 'Suggested_Type',
  'name': 'Suggested Data Type',
  'category': 'hygiene',
  'default_severity': 'Medium',
  'default_likelihood': 'Likely',
  'description': 'Data stored as text all meets criteria for a more suitable type.',
  'dq_dimension': None,
  'data_object': 'Column'},
 {'anomaly_type_id': '1002',
  'anomaly_type': 'Non_Standard_Blanks',
  'name': 'Non-Standard Blank Values',
  'category': 'hygiene',
  'default_severity': 'High',
  'default_likelihood': 'Definite',
  'description': 'Values representing missing data may be unexpected or inconsistent. Non-standard values may include '
                 'empty strings as opposed to nulls, dummy entries such as "MISSING" or repeated characters that may '
                 'have been used to bypass entry requirements, processing artifacts such as "NULL", or spreadsheet '
                 'artifacts such as "NA", "ERROR".',
  'dq_dimension': 'Completeness',
  'data_object': 'Column'},
 {'anomaly_type_id': '1003',
  'anomaly_type': 'Invalid_Zip_USA',
  'name': 'Invalid USA Zip Code Format',
  'category': 'pii',
  'default_severity': 'High',
  'default_likelihood': 'Definite',
  'description': 'Some values present do not conform with the expected format of USA Zip Codes.',
  'dq_dimension': 'Validity',
  'data_object': 'Column'},
 {'anomaly_type_id': '1004',
  'anomaly_type': 'Multiple_Types_Minor',
  'name': 'Multiple Data Types per Column Name - Minor',
  'category': 'hygiene',
  'default_severity': 'Low',
  'default_likelihood': 'Possible',
  'description': 'Columns with the same name have the same general type across tables, but the types do not exactly '
                 'match. Truncation issues may result if columns are commingled and assumed to be the same format.',
  'dq_dimension': 'Consistency',
  'data_object': 'Multi-Col'},
 {'anomaly_type_id': '1005',
  'anomaly_type': 'Multiple_Types_Major',
  'name': 'Multiple Data Types per Column Name - Major',
  'category': 'hygiene',
  'default_severity': 'Medium',
  'default_likelihood': 'Likely',
  'description': 'Columns with the same name have broadly different types across tables. Differences could be '
                 'significant enough to cause errors in downstream analysis, extra steps resulting in divergent '
                 'business logic and inconsistencies in results.',
  'dq_dimension': 'Consistency',
  'data_object': 'Multi-Col'},
 {'anomaly_type_id': '1006',
  'anomaly_type': 'No_Values',
  'name': 'No Column Values Present',
  'category': 'hygiene',
  'default_severity': 'Low',
  'default_likelihood': 'Possible',
  'description': 'This column is present in the table, but no values have been ingested or assigned in any records. '
                 'This could indicate missing data or a processing error. Note that this considers dummy values and '
                 'zero-length values as missing data.',
  'dq_dimension': 'Completeness',
  'data_object': 'Column'},
 {'anomaly_type_id': '1007',
  'anomaly_type': 'Column_Pattern_Mismatch',
  'name': 'Pattern Inconsistency Within Column',
  'category': 'hygiene',
  'default_severity': 'Medium',
  'default_likelihood': 'Likely',
  'description': 'Alpha-numeric string data within this column conforms to 2-4 different patterns, with 95% matching '
                 'the first pattern. This could indicate data errors in the remaining values.',
  'dq_dimension': 'Validity',
  'data_object': 'Column'},
 {'anomaly_type_id': '1008',
  'anomaly_type': 'Table_Pattern_Mismatch',
  'name': 'Pattern Inconsistency Across Tables',
  'category': 'hygiene',
  'default_severity': 'Medium',
  'default_likelihood': 'Likely',
  'description': 'Alpha-numeric string data within this column matches a single pattern, but other columns with the '
                 'same name have data that matches a different single pattern. Inconsistent formatting may contradict '
                 'user assumptions and cause downstream errors, extra steps and inconsistent business logic.',
  'dq_dimension': 'Validity',
  'data_object': 'Multi-Col'},
 {'anomaly_type_id': '1009',
  'anomaly_type': 'Leading_Spaces',
  'name': 'Leading Spaces Found in Column Values',
  'category': 'hygiene',
  'default_severity': 'Medium',
  'default_likelihood': 'Likely',
  'description': 'Spaces were found before data at the front of column string values. This likely contradicts user '
                 'expectations and could be a sign of broader ingestion or processing errors.',
  'dq_dimension': 'Validity',
  'data_object': 'Column'},
 {'anomaly_type_id': '1010',
  'anomaly_type': 'Quoted_Values',
  'name': 'Quoted Values Found in Column Values',
  'category': 'hygiene',
  'default_severity': 'Medium',
  'default_likelihood': 'Likely',
  'description': 'Column values were found within quotes. This likely contradicts user expectations and could be a '
                 'sign of broader ingestion or processing errors.',
  'dq_dimension': 'Validity',
  'data_object': 'Column'},
 {'anomaly_type_id': '1011',
  'anomaly_type': 'Char_Column_Number_Values',
  'name': 'Character Column with Mostly Numeric Values',
  'category': 'hygiene',
  'default_severity': 'Medium',
  'default_likelihood': 'Likely',
  'description': 'This column is defined as alpha, but more than 95% of its values are numeric. Numbers in alpha '
                 "columns won't sort correctly, and might contradict user expectations downstream. It's also possible "
                 'that more than one type of information is stored in the column, making it harder to retrieve.',
  'dq_dimension': 'Validity',
  'data_object': 'Column'},
 {'anomaly_type_id': '1012',
  'anomaly_type': 'Char_Column_Date_Values',
  'name': 'Character Column with Mostly Date Values',
  'category': 'hygiene',
  'default_severity': 'Medium',
  'default_likelihood': 'Likely',
  'description': 'This column is defined as alpha, but more than 95% of its values are dates. Dates in alpha columns '
                 "might not sort correctly, and might contradict user expectations downstream. It's also possible that "
                 'more than one type of information is stored in the column, making it harder to retrieve.',
  'dq_dimension': 'Validity',
  'data_object': 'Column'},
 {'anomaly_type_id': '1013',
  'anomaly_type': 'Small Missing Value Ct',
  'name': 'Small Percentage of Missing Values Found',
  'category': 'hygiene',
  'default_severity': 'Low',
  'default_likelihood': 'Possible',
  'description': 'Under 3% of values in this column were found to be null, zero-length or dummy values, but values are '
                 'not universally present. This could indicate unexpected missing values in a required column.',
  'dq_dimension': 'Completeness',
  'data_object': 'Column'},
 {'anomaly_type_id': '1014',
  'anomaly_type': 'Small Divergent Value Ct',
  'name': 'Small Percentage of Divergent Values Found',
  'category': 'hygiene',
  'default_severity': 'Low',
  'default_likelihood': 'Possible',
  'description': 'Under 3% of values in this column were found to be different from the most common value. This could '
                 'indicate a data error.',
  'dq_dimension': 'Validity',
  'data_object': 'Column'},
 {'anomaly_type_id': '1015',
  'anomaly_type': 'Boolean_Value_Mismatch',
  'name': 'Unexpected Boolean Values Found',
  'category': 'hygiene',
  'default_severity': 'Medium',
  'default_likelihood': 'Likely',
  'description': 'This column appears to contain boolean (True/False) data, but unexpected values were found. This '
                 'could indicate inconsistent coding for the same intended values, potentially leading to downstream '
                 'errors or inconsistent business logic.',
  'dq_dimension': 'Validity',
  'data_object': 'Column'},
 {'anomaly_type_id': '1016',
  'anomaly_type': 'Potential_Duplicates',
  'name': 'Potential Duplicate Values Found',
  'category': 'hygiene',
  'default_severity': 'Low',
  'default_likelihood': 'Possible',
  'description': 'This column is largely unique, but some duplicate values are present. This pattern is uncommon and '
                 'could indicate inadvertant duplication.',
  'dq_dimension': 'Uniqueness',
  'data_object': 'Column'},
 {'anomaly_type_id': '1017',
  'anomaly_type': 'Standardized_Value_Matches',
  'name': 'Similar Values Match When Standardized',
  'category': 'hygiene',
  'default_severity': 'Medium',
  'default_likelihood': 'Likely',
  'description': 'When column values are standardized (removing spaces, single-quotes, periods and dashes), matching '
                 'values are found in other records. This may indicate that formats should be further standardized to '
                 'allow consistent comparisons for merges, joins and roll-ups. It could also indicate the presence of '
                 'unintended duplicates.',
  'dq_dimension': 'Uniqueness',
  'data_object': 'Column'},
 {'anomaly_type_id': '1018',
  'anomaly_type': 'Unlikely_Date_Values',
  'name': 'Unlikely Dates out of Typical Range',
  'category': 'hygiene',
  'default_severity': 'Medium',
  'default_likelihood': 'Likely',
  'description': 'Some date values in this column are earlier than 1900-01-01 or later than 30 years after Profiling '
                 'date.',
  'dq_dimension': 'Accuracy',
  'data_object': 'Column'},
 {'anomaly_type_id': '1019',
  'anomaly_type': 'Recency_One_Year',
  'name': 'Recency - No Table Dates within 1 Year',
  'category': 'hygiene',
  'default_severity': 'Low',
  'default_likelihood': 'Possible',
  'description': 'Among all date columns present in the table, none fall inside of one year from Profile date.',
  'dq_dimension': 'Timeliness',
  'data_object': 'Dates'},
 {'anomaly_type_id': '1020',
  'anomaly_type': 'Recency_Six_Months',
  'name': 'Recency - No Table Dates within 6 Months',
  'category': 'hygiene',
  'default_severity': 'Low',
  'default_likelihood': 'Possible',
  'description': 'Among all date columns present in the table, the most recent date falls 6 months to 1 year back from '
                 'Profile date.',
  'dq_dimension': 'Timeliness',
  'data_object': 'Dates'},
 {'anomaly_type_id': '1021',
  'anomaly_type': 'Unexpected US States',
  'name': 'Unexpected Column Contains US States',
  'category': 'pii',
  'default_severity': 'Low',
  'default_likelihood': 'Possible',
  'description': 'This column is not labeled as a state, but contains mostly US State abbreviations. This could '
                 'indicate shifted or switched source data columns.',
  'dq_dimension': 'Consistency',
  'data_object': 'Column'},
 {'anomaly_type_id': '1022',
  'anomaly_type': 'Unexpected Emails',
  'name': 'Unexpected Column Contains Emails',
  'category': 'pii',
  'default_severity': 'Low',
  'default_likelihood': 'Possible',
  'description': 'This column is not labeled as email, but contains mostly email addresses. This could indicate '
                 'shifted or switched source data columns.',
  'dq_dimension': 'Consistency',
  'data_object': 'Column'},
 {'anomaly_type_id': '1023',
  'anomaly_type': 'Small_Numeric_Value_Ct',
  'name': 'Unexpected Numeric Values Found',
  'category': 'hygiene',
  'default_severity': 'Medium',
  'default_likelihood': 'Likely',
  'description': 'A small fraction (under 3%) of values in this column were found to be numeric. They could be '
                 'erroneous.',
  'dq_dimension': 'Validity',
  'data_object': 'Column'},
 {'anomaly_type_id': '1024',
  'anomaly_type': 'Invalid_Zip3_USA',
  'name': 'Invalid USA ZIP-3 Format',
  'category': 'pii',
  'default_severity': 'High',
  'default_likelihood': 'Definite',
  'description': 'The majority of values in this column are 3-digit zips, but divergent patterns were found. This '
                 'could indicate an incorrect roll-up category or a PII concern.',
  'dq_dimension': 'Validity',
  'data_object': 'Column'},
 {'anomaly_type_id': '1025',
  'anomaly_type': 'Delimited_Data_Embedded',
  'name': 'Delimited Data Embedded in Column',
  'category': 'hygiene',
  'default_severity': 'Medium',
  'default_likelihood': 'Likely',
  'description': 'Delimited data, separated by a common delimiter (comma, tab, pipe or caret) is present in over 80% '
                 'of column values. This could indicate data that was incorrectly ingested, or data that would be '
                 'better represented in parsed form.',
  'dq_dimension': 'Validity',
  'data_object': 'Column'},
 {'anomaly_type_id': '1026',
  'anomaly_type': 'Char_Column_Number_Units',
  'name': 'Character Column with Numbers and Units',
  'category': 'hygiene',
  'default_severity': 'Low',
  'default_likelihood': 'Possible',
  'description': 'This column is defined as alpha, but values include numbers with percents or common units. Embedded '
                 "measures in alpha columns are harder to access, won't sort correctly, and might contradict user "
                 'expectations downstream. Consider parsing into numeric and UOM columns to improve usability.',
  'dq_dimension': 'Consistency',
  'data_object': 'Column'},
 {'anomaly_type_id': '1027',
  'anomaly_type': 'Variant_Coded_Values',
  'name': 'Variant Codings for Same Values',
  'category': 'hygiene',
  'default_severity': 'High',
  'default_likelihood': 'Definite',
  'description': 'This column contains more than one common variants that represent a single value or state. This can '
                 'occur when data is integrated from multiple sources with different standards, or when free entry is '
                 'permitted without validation. The variations can cause confusion and error for downstream data users '
                 'and multiple versions of the truth.',
  'dq_dimension': 'Consistency',
  'data_object': 'Variant'},
 {'anomaly_type_id': '1028',
  'anomaly_type': 'Inconsistent_Casing',
  'name': 'Inconsistent Casing',
  'category': 'hygiene',
  'default_severity': 'High',
  'default_likelihood': 'Definite',
  'description': 'Casing is inconsistent for a column representing an entity name or address elements. Mixed-Case and '
                 'All-Upper-Case values were found in the same column.',
  'dq_dimension': 'Validity',
  'data_object': 'Column'},
 {'anomaly_type_id': '1029',
  'anomaly_type': 'Non_Alpha_Name_Address',
  'name': 'Non-Alpha Name or Address',
  'category': 'pii',
  'default_severity': 'High',
  'default_likelihood': 'Definite',
  'description': 'Entirely non-alphabetic values were found in a column representing an entity name or address '
                 'element.',
  'dq_dimension': 'Validity',
  'data_object': 'Column'},
 {'anomaly_type_id': '1030',
  'anomaly_type': 'Non_Alpha_Prefixed_Name',
  'name': 'Non-Alpha Prefixed Name',
  'category': 'pii',
  'default_severity': 'High',
  'default_likelihood': 'Definite',
  'description': 'Non-alphabetic characters were found at the start of a column representing an entity name.',
  'dq_dimension': 'Validity',
  'data_object': 'Column'},
 {'anomaly_type_id': '1031',
  'anomaly_type': 'Non_Printing_Chars',
  'name': 'Non-Printing Characters',
  'category': 'hygiene',
  'default_severity': 'High',
  'default_likelihood': 'Definite',
  'description': 'Non-printing characters were found embedded in a text column.',
  'dq_dimension': 'Validity',
  'data_object': 'Column'},
 {'anomaly_type_id': '1100',
  'anomaly_type': 'Potential_PII',
  'name': 'Personally Identifiable Information',
  'category': 'pii',
  'default_severity': 'High',
  'default_likelihood': 'Potential PII',
  'description': 'This column contains data that could be Personally Identifiable Information (PII)',
  'dq_dimension': 'Validity',
  'data_object': 'Column'}]
